export interface Exhibitor {
  id: string;
  name: string;
  stand: string;
  logo: string;
  favAdd: string;
  favRemove: string;
  category: string;
  isPVInstaller: boolean;
  status: 'New' | 'Contacted' | 'Successful Lead' | 'Rejected';
  notes: string;
  website: string;
  reservedArea: string;
}

export const initialExhibitors: Exhibitor[] = [
  {
    "id": "6883027",
    "name": "A.D.N.A TECHNOLOGY B.V",
    "stand": "A5/334",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6883027",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6883027",
    "website": "https://www.dpeurope.it/en/profile-detail/ADNA%20TECHNOLOGY%20BV?digitalProfileId=6883027",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352180",
    "name": "AB TRASMISSIONI SRL",
    "stand": "A5/141",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_AB_TRASMISSIONI_SRL_logo_6998454b32ad2.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352180",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352180",
    "website": "https://www.dpeurope.it/en/profile-detail/AB%20TRASMISSIONI%20SRL?digitalProfileId=6352180",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6917509",
    "name": "AFME",
    "stand": "A5/226",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6917509",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6917509",
    "website": "https://www.dpeurope.it/en/profile-detail/AFME?digitalProfileId=6917509",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "7029306",
    "name": "AISCAN",
    "stand": "A5/226",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_AISCAN___logo_6989c367617de.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/7029306",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/7029306",
    "website": "https://www.dpeurope.it/en/profile-detail/AISCAN?digitalProfileId=7029306",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6904774",
    "name": "ANHUI CHARDON ELECTRIC LTD.",
    "stand": "A5/553",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_ANHUI_CHARDON_ELECTRIC_LTD._logo_698d81939d21b.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6904774",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6904774",
    "website": "https://www.dpeurope.it/en/profile-detail/ANHUI%20CHARDON%20ELECTRIC%20LTD?digitalProfileId=6904774",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "7132944",
    "name": "ANIE Federazione",
    "stand": "A5/240",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_ANIE_SERVIZI_INTEGRATI_S.R.L.___logo_699f086018e9b.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/7132944",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/7132944",
    "website": "https://www.dpeurope.it/en/profile-detail/ANIE%20Federazione?digitalProfileId=7132944",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352199",
    "name": "ASSOCIAZIONE GENERAZIONE DISTRIBUITA",
    "stand": "A5/241",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352199",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352199",
    "website": "https://www.dpeurope.it/en/profile-detail/ASSOCIAZIONE%20GENERAZIONE%20DISTRIBUITA?digitalProfileId=6352199",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352187",
    "name": "BIMOTOR",
    "stand": "A5/137",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352187",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352187",
    "website": "https://www.dpeurope.it/en/profile-detail/BIMOTOR?digitalProfileId=6352187",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6899820",
    "name": "Boffetti S.p.A.",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6899820",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6899820",
    "website": "https://www.dpeurope.it/en/represented-company/Boffetti%20SpA?representedCompanyId=6899820",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6877189",
    "name": "BONOMEDIA SRL  - RERTECH SRL",
    "stand": "A5/135",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6877189",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6877189",
    "website": "https://www.dpeurope.it/en/profile-detail/BONOMEDIA%20SRL%20%20-%20RERTECH%20SRL?digitalProfileId=6877189",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6722068",
    "name": "BQUADRI SRL",
    "stand": "A5/129",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_BQUADRI_SRL_logo_697d0a3c46b0a.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6722068",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6722068",
    "website": "https://www.dpeurope.it/en/profile-detail/BQUADRI%20SRL?digitalProfileId=6722068",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352203",
    "name": "BRUNO SRL",
    "stand": "A5/150",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_BRUNO_SRL_logo_6989c77d64607.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352203",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352203",
    "website": "https://www.dpeurope.it/en/profile-detail/BRUNO%20SRL?digitalProfileId=6352203",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6614517",
    "name": "BYM SRL",
    "stand": "A5/130",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6614517",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6614517",
    "website": "https://www.dpeurope.it/en/profile-detail/BYM%20SRL?digitalProfileId=6614517",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352181",
    "name": "CGM GRUPPI ELETTROGENI SRL",
    "stand": "A5/452",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352181",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352181",
    "website": "https://www.dpeurope.it/en/profile-detail/CGM%20GRUPPI%20ELETTROGENI%20SRL?digitalProfileId=6352181",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352186",
    "name": "COELMO SPA",
    "stand": "A5/140",
    "logo": "https://www.dpeurope.it/_default_upload_bucket/Logo%20Coelmo.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352186",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352186",
    "website": "https://www.dpeurope.it/en/profile-detail/COELMO%20SPA?digitalProfileId=6352186",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352427",
    "name": "CR TECHNOLOGY SYSTEMS S.P.A",
    "stand": "A5/111",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_CR_TECHNOLOGY_SYSTEMS_S.P.A_logo_69899ba834c36.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352427",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352427",
    "website": "https://www.dpeurope.it/en/profile-detail/CR%20TECHNOLOGY%20SYSTEMS%20SPA?digitalProfileId=6352427",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "7043570",
    "name": "CUMMINS ITALIA SPA",
    "stand": "A5/550",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_CUMMINS_ITALIA_SPA_logo_699c44e097322.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/7043570",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/7043570",
    "website": "https://www.dpeurope.it/en/profile-detail/CUMMINS%20ITALIA%20SPA?digitalProfileId=7043570",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6896365",
    "name": "EGSYSTEM SRL",
    "stand": "A5/110",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6896365",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6896365",
    "website": "https://www.dpeurope.it/en/profile-detail/EGSYSTEM%20SRL?digitalProfileId=6896365",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6614520",
    "name": "ELECNOR SERVICIOS Y PROYECTOS SAU",
    "stand": "A5/210",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_ELECNOR_SERVICIOS_Y_PROYECTOS_SAU_logo_698b157145f30.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6614520",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6614520",
    "website": "https://www.dpeurope.it/en/profile-detail/ELECNOR%20SERVICIOS%20Y%20PROYECTOS%20SAU?digitalProfileId=6614520",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6508959",
    "name": "ELPACK SPA",
    "stand": "A5/341",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6508959",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6508959",
    "website": "https://www.dpeurope.it/en/profile-detail/ELPACK%20SPA?digitalProfileId=6508959",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6877190",
    "name": "ETM GROUP",
    "stand": "A5/546",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_ETM_SRL_logo_697a3fbedc151.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6877190",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6877190",
    "website": "https://www.dpeurope.it/en/profile-detail/ETM%20GROUP?digitalProfileId=6877190",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6508960",
    "name": "GB SERVICES SRL",
    "stand": "A5/327",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_GB_SERVICES_SRL___logo_699c6c8220d84.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6508960",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6508960",
    "website": "https://www.dpeurope.it/en/profile-detail/GB%20SERVICES%20SRL?digitalProfileId=6508960",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6896366",
    "name": "GETAC",
    "stand": "A5/207",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_GETAC_TECHNOLOGY_CORPORATION___logo_698469793bee7.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6896366",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6896366",
    "website": "https://www.dpeurope.it/en/profile-detail/GETAC?digitalProfileId=6896366",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6899924",
    "name": "GMR ENLIGHTS s.r.l.",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6899924",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6899924",
    "website": "https://www.dpeurope.it/en/represented-company/GMR%20ENLIGHTS%20srl?representedCompanyId=6899924",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352185",
    "name": "GREEN POWER SYSTEMS SRL",
    "stand": "A5/139",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_GREEN_POWER_SYSTEMS_SRL_logo_69788cfd3bbbe.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352185",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352185",
    "website": "https://www.dpeurope.it/en/profile-detail/GREEN%20POWER%20SYSTEMS%20SRL?digitalProfileId=6352185",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6725467",
    "name": "HENAN DINGLI POWER EQUIPMENT CO., LTD",
    "stand": "A5/145",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_Henan_Dingli_Power_Equipment_Co.__Ltd___logo_697afc868fbba.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6725467",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6725467",
    "website": "https://www.dpeurope.it/en/profile-detail/HENAN%20DINGLI%20POWER%20EQUIPMENT%20CO%20LTD?digitalProfileId=6725467",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6910525",
    "name": "ILVIEF S.A.",
    "stand": "A5/100",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_ILVIEF_S.A.___logo_699f0258ec5bd.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6910525",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6910525",
    "website": "https://www.dpeurope.it/en/profile-detail/ILVIEF%20SA?digitalProfileId=6910525",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352434",
    "name": "inavitas Energy",
    "stand": "A5/206",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_INAVITAS_ENERJI_A.s.___logo_6979aa78b899f.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352434",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352434",
    "website": "https://www.dpeurope.it/en/profile-detail/inavitas%20Energy?digitalProfileId=6352434",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6411450",
    "name": "ITALCLEM SRL",
    "stand": "A5/106",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_ITALCLEM_SRL_logo_69821e76e2364.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6411450",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6411450",
    "website": "https://www.dpeurope.it/en/profile-detail/ITALCLEM%20SRL?digitalProfileId=6411450",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352182",
    "name": "MECC ALTE SPA",
    "stand": "A5/124A",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_MECC_ALTE_SPA_logo_699d85b6b61e5.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352182",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352182",
    "website": "https://www.dpeurope.it/en/profile-detail/MECC%20ALTE%20SPA?digitalProfileId=6352182",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352175",
    "name": "MECCANICA COUPLINGS  SRL",
    "stand": "A5/541",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_MECCANICA_COUPLINGS__SRL_logo_6989e6f78ae1e.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352175",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352175",
    "website": "https://www.dpeurope.it/en/profile-detail/MECCANICA%20COUPLINGS%20%20SRL?digitalProfileId=6352175",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352193",
    "name": "MIRETTI GROUP",
    "stand": "A5/307",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_MIRETTI_SRL_logo_6978b9f2584cc.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352193",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352193",
    "website": "https://www.dpeurope.it/en/profile-detail/MIRETTI%20GROUP?digitalProfileId=6352193",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "7112401",
    "name": "O.L.F. SRL",
    "stand": "A5/144",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/7112401",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/7112401",
    "website": "https://www.dpeurope.it/en/profile-detail/OLF%20SRL?digitalProfileId=7112401",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6355077",
    "name": "Penta Electrical Safety Products Italia Srl",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_WORK_ITALIA_SRL_logo_69a028d9655b4.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6355077",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6355077",
    "website": "https://www.dpeurope.it/en/profile-detail/Penta%20Electrical%20Safety%20Products%20Italia%20Srl?digitalProfileId=6355077",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6917510",
    "name": "PORTALAMPARAS Y ACCESORIOS SOLERA S.A.U",
    "stand": "A5/226",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_PORTALAMPARAS_Y_ACCESORIOS_SOLERA_S.A.U___logo_69898d25d6ddd.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6917510",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6917510",
    "website": "https://www.dpeurope.it/en/profile-detail/PORTALAMPARAS%20Y%20ACCESORIOS%20SOLERA%20SAU?digitalProfileId=6917510",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352194",
    "name": "PRECABL SRL",
    "stand": "A5/420",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352194",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352194",
    "website": "https://www.dpeurope.it/en/profile-detail/PRECABL%20SRL?digitalProfileId=6352194",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6355075",
    "name": "REFI SRL",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_REFI_SRL_logo_6971e2ba0eed2.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6355075",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6355075",
    "website": "https://www.dpeurope.it/en/profile-detail/REFI%20SRL?digitalProfileId=6355075",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6355076",
    "name": "REPL ITALIA SRL",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6355076",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6355076",
    "website": "https://www.dpeurope.it/en/profile-detail/REPL%20ITALIA%20SRL?digitalProfileId=6355076",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6543494",
    "name": "SAMI TRAFO AŞ",
    "stand": "A5/225",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6543494",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6543494",
    "website": "https://www.dpeurope.it/en/profile-detail/SAMI%20TRAFO%20A?digitalProfileId=6543494",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6910526",
    "name": "SANERGRID",
    "stand": "A5/542",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_SANERGRID___logo_6985fcd146ef8.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6910526",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6910526",
    "website": "https://www.dpeurope.it/en/profile-detail/SANERGRID?digitalProfileId=6910526",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6669751",
    "name": "SEL SPA",
    "stand": "A5/120",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_SEL_SPA_logo_698daa12875ce.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6669751",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6669751",
    "website": "https://www.dpeurope.it/en/profile-detail/SEL%20SPA?digitalProfileId=6669751",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6722069",
    "name": "Shandong Taikai Transformer Co., Ltd.",
    "stand": "A5/220",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_Shandong_Taikai_Transformer_Company_Ltd.___logo_69894b9c2d466.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6722069",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6722069",
    "website": "https://www.dpeurope.it/en/profile-detail/Shandong%20Taikai%20Transformer%20Co%20Ltd?digitalProfileId=6722069",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6725468",
    "name": "Shuangdeng Cable Co.,Ltd",
    "stand": "A5/124",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_SHUANGDENG_GROUP_CO._LTD_logo_697afa8bd16f2.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6725468",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6725468",
    "website": "https://www.dpeurope.it/en/profile-detail/Shuangdeng%20Cable%20CoLtd?digitalProfileId=6725468",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6873919",
    "name": "SIEYUAN ELECTRIC CO., LTD.",
    "stand": "A5/331",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_SHANGHAI_SIEYUAN_WATTEN_TECHNOLOGY_CO_LTD___logo_69897433e7366.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6873919",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6873919",
    "website": "https://www.dpeurope.it/en/profile-detail/SIEYUAN%20ELECTRIC%20CO%20LTD?digitalProfileId=6873919",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6543495",
    "name": "SINCRO",
    "stand": "A5/121",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_SINCRO_logo_696f9c3f1bc53.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6543495",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6543495",
    "website": "https://www.dpeurope.it/en/profile-detail/SINCRO?digitalProfileId=6543495",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352178",
    "name": "SOCOGES SRL",
    "stand": "A5/143",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352178",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352178",
    "website": "https://www.dpeurope.it/en/profile-detail/SOCOGES%20SRL?digitalProfileId=6352178",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6716518",
    "name": "SORTIMO ITALIA SRL",
    "stand": "PISCINE OVEST/004",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_SORTIMO_ITALIA_SRL_logo_697b924053be1.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6716518",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6716518",
    "website": "https://www.dpeurope.it/en/profile-detail/SORTIMO%20ITALIA%20SRL?digitalProfileId=6716518",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352447",
    "name": "TECSYSTEM SRL",
    "stand": "A5/230",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_TECSYSTEM_SRL_logo_69737cc24e484.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352447",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352447",
    "website": "https://www.dpeurope.it/en/profile-detail/TECSYSTEM%20SRL?digitalProfileId=6352447",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6899872",
    "name": "Tesmec Automation Srl",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6899872",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6899872",
    "website": "https://www.dpeurope.it/en/represented-company/Tesmec%20Automation%20Srl?representedCompanyId=6899872",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6614523",
    "name": "THYTRONIC SPA",
    "stand": "A5/059",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_THYTRONIC_SPA___logo_696f887887048.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6614523",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6614523",
    "website": "https://www.dpeurope.it/en/profile-detail/THYTRONIC%20SPA?digitalProfileId=6614523",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6899776",
    "name": "TMC TRANSFORMERS S.p.A.",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6899776",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6899776",
    "website": "https://www.dpeurope.it/en/represented-company/TMC%20TRANSFORMERS%20SpA?representedCompanyId=6899776",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6917511",
    "name": "TOSCANO",
    "stand": "A5/222",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_TOSCANO___logo_6989c60a38ad2.jpg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6917511",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6917511",
    "website": "https://www.dpeurope.it/en/profile-detail/TOSCANO?digitalProfileId=6917511",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6352204",
    "name": "TransizioneElettrica.it",
    "stand": "A5/552",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_DBINFORMATION_SPA_logo_698f3c602a82a.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6352204",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6352204",
    "website": "https://www.dpeurope.it/en/profile-detail/TransizioneElettricait?digitalProfileId=6352204",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "6411453",
    "name": "UNEX",
    "stand": "A5/325",
    "logo": "https://www.dpeurope.it/restricted-assets/digital-profiles/DPE26/DPE26_UNEX_APARELLAJE_EL__CTRICO__S.L.___logo_6968b5a90d5a6.png",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/6411453",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/6411453",
    "website": "https://www.dpeurope.it/en/profile-detail/UNEX?digitalProfileId=6411453",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  },
  {
    "id": "7054649",
    "name": "VOLTA MACCHINE SRL",
    "stand": "A5/200",
    "logo": "https://www.dpeurope.it/Data/DPE/LOGHI/LOGO-DPE-BLU%2003.svg",
    "favAdd": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/add/7054649",
    "favRemove": "https://www.dpeurope.it/en/reserved-area/exhibitors/favourites/remove/7054649",
    "website": "https://www.dpeurope.it/en/profile-detail/VOLTA%20MACCHINE%20SRL?digitalProfileId=7054649",
    "reservedArea": "https://www.dpeurope.it/en/reserved-area",
    "category": "Exhibitor",
    "isPVInstaller": false,
    "status": "New",
    "notes": ""
  }
];
